package constant;

import java.util.HashMap;
import java.util.Map;

public class Permission {
    public static Map<String, String> permissionToMessage = new HashMap<>();

    public static Map<String, String> permissionToProperty = new HashMap<>();

    static {
        permissionToMessage.put("ACCEPT_HANDOVER", "允许呼叫应用在另一个应用中启动。");
        permissionToProperty.put("ACCEPT_HANDOVER", "jump");
        permissionToMessage.put("ACCESS_BACKGROUND_LOCATION", "允许应用在后台访问位置信息。");
        permissionToProperty.put("ACCESS_BACKGROUND_LOCATION", "location");
        permissionToMessage.put("ACCESS_BLOBS_ACROSS_USERS", "允许应用程序跨用户访问数据 blob。");
        permissionToProperty.put("ACCESS_BLOBS_ACROSS_USERS", "user");
        permissionToMessage.put("ACCESS_CHECKIN_PROPERTIES", "允许对登记中的“属性”表进行读/写访问数据库，用于更改上面的值。");
        permissionToProperty.put("ACCESS_CHECKIN_PROPERTIES", "read");
        permissionToMessage.put("ACCESS_COARSE_LOCATION", "允许应用访问大致位置。");
        permissionToProperty.put("ACCESS_COARSE_LOCATION", "location");
        permissionToMessage.put("ACCESS_FINE_LOCATION", "允许应用访问精确位置。");
        permissionToProperty.put("ACCESS_FINE_LOCATION", "location");
        permissionToMessage.put("ACCESS_LOCATION_EXTRA_COMMANDS", "允许应用程序访问额外的位置提供程序命令。");
        permissionToProperty.put("ACCESS_LOCATION_EXTRA_COMMANDS", "path");
        permissionToMessage.put("ACCESS_MEDIA_LOCATION", "允许应用程序访问保留在用户的共享集合。");
        permissionToProperty.put("ACCESS_MEDIA_LOCATION", "path");
        permissionToMessage.put("ACCESS_NETWORK_STATE", "允许应用程序访问有关网络的信号。");
        permissionToProperty.put("ACCESS_NETWORK_STATE", "net");
        permissionToMessage.put("ACCESS_NOTIFICATION_POLICY", "希望访问通知策略的应用程序的标记权限。");
        permissionToProperty.put("ACCESS_NOTIFICATION_POLICY", "notify");
        permissionToMessage.put("ACCESS_WIFI_STATE", "允许应用程序访问有关 Wi-Fi 网络的信息。");
        permissionToProperty.put("ACCESS_WIFI_STATE", "wifi");
        permissionToMessage.put("ACCOUNT_MANAGER", "允许应用程序调用帐户身份验证器。");
        permissionToProperty.put("ACCOUNT_MANAGER", "user");
        permissionToMessage.put("ACTIVITY_RECOGNITION", "允许应用程序识别身体活动。");
        permissionToProperty.put("ACTIVITY_RECOGNITION", "recog");
        permissionToMessage.put("ADD_VOICEMAIL", "允许应用程序将语音邮件添加到系统中。");
        permissionToProperty.put("ADD_VOICEMAIL", "mail");
        permissionToMessage.put("ANSWER_PHONE_CALLS", "允许应用应答来电。");
        permissionToProperty.put("ANSWER_PHONE_CALLS", "call");
        permissionToMessage.put("BATTERY_STATS", "允许应用程序收集电池统计信息。");
        permissionToProperty.put("BATTERY_STATS", "device");
        permissionToMessage.put("BIND_ACCESSIBILITY_SERVICE", "暂无。");
        permissionToProperty.put("BIND_ACCESSIBILITY_SERVICE", "bind");
        permissionToMessage.put("BIND_APPWIDGET", "允许应用程序告诉 AppWidget ，哪个应用程序 可以访问 AppWidget 的数据。");
        permissionToProperty.put("BIND_APPWIDGET", "widget");
        permissionToMessage.put("BIND_AUTOFILL_SERVICE", "暂无。");
        permissionToProperty.put("BIND_AUTOFILL_SERVICE", "bind");
        permissionToMessage.put("BIND_CALL_REDIRECTION_SERVICE", "暂无。");
        permissionToProperty.put("BIND_CALL_REDIRECTION_SERVICE", "bind");
        permissionToMessage.put("BIND_CARRIER_MESSAGING_CLIENT_SERVICE", "暂无。");
        permissionToProperty.put("BIND_CARRIER_MESSAGING_CLIENT_SERVICE", "bind");
        permissionToMessage.put("BIND_CARRIER_MESSAGING_SERVICE", "暂无。");
        permissionToProperty.put("BIND_CARRIER_MESSAGING_SERVICE", "bind");
        permissionToMessage.put("BIND_CARRIER_SERVICES", "暂无。");
        permissionToProperty.put("BIND_CARRIER_SERVICES", "bind");
        permissionToMessage.put("BIND_CHOOSER_TARGET_SERVICE", "暂无。");
        permissionToProperty.put("BIND_CHOOSER_TARGET_SERVICE", "bind");
        permissionToMessage.put("BIND_COMPANION_DEVICE_SERVICE", "暂无。");
        permissionToProperty.put("BIND_COMPANION_DEVICE_SERVICE", "bind");
        permissionToMessage.put("BIND_CONDITION_PROVIDER_SERVICE", "暂无。");
        permissionToProperty.put("BIND_CONDITION_PROVIDER_SERVICE", "bind");
        permissionToMessage.put("BIND_CONTROLS", "暂无。");
        permissionToProperty.put("BIND_CONTROLS", "bind");
        permissionToMessage.put("BIND_CREDENTIAL_PROVIDER_SERVICE", "暂无。");
        permissionToProperty.put("BIND_CREDENTIAL_PROVIDER_SERVICE", "bind");
        permissionToMessage.put("BIND_DEVICE_ADMIN", "暂无。");
        permissionToProperty.put("BIND_DEVICE_ADMIN", "bind");
        permissionToMessage.put("BIND_DREAM_SERVICE", "暂无。");
        permissionToProperty.put("BIND_DREAM_SERVICE", "bind");
        permissionToMessage.put("BIND_INCALL_SERVICE", "暂无。");
        permissionToProperty.put("BIND_INCALL_SERVICE", "bind");
        permissionToMessage.put("BIND_INPUT_METHOD", "暂无。");
        permissionToProperty.put("BIND_INPUT_METHOD", "bind");
        permissionToMessage.put("BIND_MIDI_DEVICE_SERVICE", "暂无。");
        permissionToProperty.put("BIND_MIDI_DEVICE_SERVICE", "bind");
        permissionToMessage.put("BIND_NFC_SERVICE", "暂无。");
        permissionToProperty.put("BIND_NFC_SERVICE", "bind");
        permissionToMessage.put("BIND_NOTIFICATION_LISTENER_SERVICE", "暂无。");
        permissionToProperty.put("BIND_NOTIFICATION_LISTENER_SERVICE", "bind");
        permissionToMessage.put("BIND_PRINT_SERVICE", "暂无。");
        permissionToProperty.put("BIND_PRINT_SERVICE", "bind");
        permissionToMessage.put("BIND_QUICK_ACCESS_WALLET_SERVICE", "暂无。");
        permissionToProperty.put("BIND_QUICK_ACCESS_WALLET_SERVICE", "bind");
        permissionToMessage.put("BIND_QUICK_SETTINGS_TILE", "暂无。");
        permissionToProperty.put("BIND_QUICK_SETTINGS_TILE", "bind");
        permissionToMessage.put("BIND_REMOTEVIEWS", "暂无。");
        permissionToProperty.put("BIND_REMOTEVIEWS", "bind");
        permissionToMessage.put("BIND_SCREENING_SERVICE", "暂无。");
        permissionToProperty.put("BIND_SCREENING_SERVICE", "bind");
        permissionToMessage.put("BIND_TELECOM_CONNECTION_SERVICE", "暂无。");
        permissionToProperty.put("BIND_TELECOM_CONNECTION_SERVICE", "bind");
        permissionToMessage.put("BIND_TEXT_SERVICE", "暂无。");
        permissionToProperty.put("BIND_TEXT_SERVICE", "bind");
        permissionToMessage.put("BIND_TV_INPUT", "暂无。");
        permissionToProperty.put("BIND_TV_INPUT", "bind");
        permissionToMessage.put("BIND_TV_INTERACTIVE_APP", "暂无。");
        permissionToProperty.put("BIND_TV_INTERACTIVE_APP", "bind");
        permissionToMessage.put("BIND_VISUAL_VOICEMAIL_SERVICE", "暂无。");
        permissionToProperty.put("BIND_VISUAL_VOICEMAIL_SERVICE", "bind");
        permissionToMessage.put("BIND_VOICE_INTERACTION", "暂无。");
        permissionToProperty.put("BIND_VOICE_INTERACTION", "bind");
        permissionToMessage.put("BIND_VPN_SERVICE", "暂无。");
        permissionToProperty.put("BIND_VPN_SERVICE", "bind");
        permissionToMessage.put("BIND_VR_LISTENER_SERVICE", "暂无。");
        permissionToProperty.put("BIND_VR_LISTENER_SERVICE", "bind");
        permissionToMessage.put("BIND_WALLPAPER", "暂无。");
        permissionToProperty.put("BIND_WALLPAPER", "bind");
        permissionToMessage.put("BLUETOOTH", "允许应用程序连接到配对的蓝牙设备。");
        permissionToProperty.put("BLUETOOTH", "bluetooth");
        permissionToMessage.put("BLUETOOTH_ADMIN", "允许应用程序发现和配对蓝牙设备。");
        permissionToProperty.put("BLUETOOTH_ADMIN", "bluetooth");
        permissionToMessage.put("BLUETOOTH_ADVERTISE", "需要能够向附近的蓝牙设备播发。");
        permissionToProperty.put("BLUETOOTH_ADVERTISE", "bluetooth");
        permissionToMessage.put("BLUETOOTH_CONNECT", "需要能够连接到配对的蓝牙设备。");
        permissionToProperty.put("BLUETOOTH_CONNECT", "bluetooth");
        permissionToMessage.put("BLUETOOTH_PRIVILEGED", "允许应用程序在没有用户交互的情况时配对蓝牙设备，并允许或禁止电话簿访问或消息访问。");
        permissionToProperty.put("BLUETOOTH_PRIVILEGED", "bluetooth");
        permissionToMessage.put("BLUETOOTH_SCAN", "需要能够发现和配对附近的蓝牙设备。");
        permissionToProperty.put("BLUETOOTH_SCAN", "bluetooth");
        permissionToMessage.put("BODY_SENSORS", "允许应用程序从用户使用的传感器访问数据，测量他们体内发生的事情，例如心率。");
        permissionToProperty.put("BODY_SENSORS", "sensor");
        permissionToMessage.put("BODY_SENSORS_BACKGROUND", "允许应用程序在后台从用户使用的传感器访问数据，测量他们体内发生的事情，例如心率。");
        permissionToProperty.put("BODY_SENSORS_BACKGROUND", "sensor");
        permissionToMessage.put("BODY_SENSORS_WRIST_TEMPERATURE", "允许应用程序从手表传感器访问手腕温度数据。");
        permissionToProperty.put("BODY_SENSORS_WRIST_TEMPERATURE", "sensor");
        permissionToMessage.put("BODY_SENSORS_WRIST_TEMPERATURE_BACKGROUND", "允许应用程序从手表传感器访问手腕温度数据。");
        permissionToProperty.put("BODY_SENSORS_WRIST_TEMPERATURE_BACKGROUND", "sensor");
        permissionToMessage.put("BROADCAST_PACKAGE_REMOVED", "允许应用程序广播应用程序通知包已被删除。");
        permissionToProperty.put("BROADCAST_PACKAGE_REMOVED", "broad");
        permissionToMessage.put("BROADCAST_SMS", "允许应用程序广播短信接收通知。");
        permissionToProperty.put("BROADCAST_SMS", "broad");
        permissionToMessage.put("BROADCAST_STICKY", "允许应用程序广播粘性意向。");
        permissionToProperty.put("BROADCAST_STICKY", "broad");
        permissionToMessage.put("BROADCAST_WAP_PUSH", "允许应用程序广播WAP推送接收通知。");
        permissionToProperty.put("BROADCAST_WAP_PUSH", "broad");
        permissionToMessage.put("CALL_COMPANION_APP", "允许实现 API 的应用有资格作为呼叫伴侣应用。");
        permissionToProperty.put("CALL_COMPANION_APP", "jump");
        permissionToMessage.put("CALL_PHONE", "允许应用程序在不通过的情况下发起电话呼叫拨号器用户界面，供用户确认呼叫。");
        permissionToProperty.put("CALL_PHONE", "call");
        permissionToMessage.put("CALL_PRIVILEGED", "允许应用程序呼叫任何电话号码，包括紧急情况 数字，无需通过用户的拨号器用户界面 以确认正在发出的呼叫。");
        permissionToProperty.put("CALL_PRIVILEGED", "call");
        permissionToMessage.put("CAMERA", "需要能够访问相机设备。");
        permissionToProperty.put("CAMERA", "camera");
        permissionToMessage.put("CAPTURE_AUDIO_OUTPUT", "允许应用程序捕获音频输出。");
        permissionToProperty.put("CAPTURE_AUDIO_OUTPUT", "audio");
        permissionToMessage.put("CHANGE_COMPONENT_ENABLED_STATE", "允许应用程序更改应用程序组件（而不是其自身组件）是否为启用与否。");
        permissionToProperty.put("CHANGE_COMPONENT_ENABLED_STATE", "change");
        permissionToMessage.put("CHANGE_CONFIGURATION", "允许应用程序修改当前配置，例如 作为区域设置。");
        permissionToProperty.put("CHANGE_CONFIGURATION", "change");
        permissionToMessage.put("CHANGE_NETWORK_STATE", "允许应用程序更改网络连接状态。");
        permissionToProperty.put("CHANGE_NETWORK_STATE", "net");
        permissionToMessage.put("CHANGE_WIFI_MULTICAST_STATE", "允许应用程序进入 Wi-Fi 多播模式。");
        permissionToProperty.put("CHANGE_WIFI_MULTICAST_STATE", "wifi");
        permissionToMessage.put("CHANGE_WIFI_STATE", "允许应用程序更改 Wi-Fi 连接状态。");
        permissionToProperty.put("CHANGE_WIFI_STATE", "wifi");
        permissionToMessage.put("CLEAR_APP_CACHE", "允许应用程序清除所有已安装的缓存设备上的应用程序。");
        permissionToProperty.put("CLEAR_APP_CACHE", "cache");
        permissionToMessage.put("CONFIGURE_WIFI_DISPLAY", "允许应用程序配置和连接到 Wifi 显示器");
        permissionToProperty.put("CONFIGURE_WIFI_DISPLAY", "wifi");
        permissionToMessage.put("CONTROL_LOCATION_UPDATES", "允许启用/禁用位置更新通知。");
        permissionToProperty.put("CONTROL_LOCATION_UPDATES", "location");
        permissionToMessage.put("CREDENTIAL_MANAGER_SET_ORIGIN", "允许浏览器代表另一个 RP 调用凭据管理器 API。");
        permissionToProperty.put("CREDENTIAL_MANAGER_SET_ORIGIN", "change");
        permissionToMessage.put("DELETE_CACHE_FILES", "删除应用缓存文件的旧权限，不再使用， 但信号让我们安静地忽略呼叫，而不是抛出异常。");
        permissionToProperty.put("DELETE_CACHE_FILES", "cache");
        permissionToMessage.put("DELETE_PACKAGES", "允许应用程序删除包。");
        permissionToProperty.put("DELETE_PACKAGES", "delete");
        permissionToMessage.put("DELIVER_COMPANION_MESSAGES", "允许应用程序将伴随消息传递到系统");
        permissionToProperty.put("DELIVER_COMPANION_MESSAGES", "message");
        permissionToMessage.put("DETECT_SCREEN_CAPTURE", "允许应用程序在尝试捕获其窗口的屏幕时收到通知。");
        permissionToProperty.put("DETECT_SCREEN_CAPTURE", "screen");
        permissionToMessage.put("DIAGNOSTIC", "允许应用程序 RW 到诊断资源。");
        permissionToProperty.put("DIAGNOSTIC", "path");
        permissionToMessage.put("DISABLE_KEYGUARD", "允许应用程序在键盘安全的情况下禁用键盘锁。");
        permissionToProperty.put("DISABLE_KEYGUARD", "key");
        permissionToMessage.put("DUMP", "允许应用程序从系统服务检索状态转储信息。");
        permissionToProperty.put("DUMP", "path");
        permissionToMessage.put("ENFORCE_UPDATE_OWNERSHIP", "允许应用程序成为更新所有者。");
        permissionToProperty.put("ENFORCE_UPDATE_OWNERSHIP", "owner");
        permissionToMessage.put("EXECUTE_APP_ACTION", "允许辅助应用程序代表 应用。");
        permissionToProperty.put("EXECUTE_APP_ACTION", "owner");
        permissionToMessage.put("EXPAND_STATUS_BAR", "允许应用程序展开或折叠状态栏。");
        permissionToProperty.put("EXPAND_STATUS_BAR", "bar");
        permissionToMessage.put("FACTORY_TEST", "作为制造商测试应用程序运行，以根用户身份运行。");
        permissionToProperty.put("FACTORY_TEST", "test");
        permissionToMessage.put("FOREGROUND_SERVICE", "允许常规应用程序使用置顶功能。");
        permissionToProperty.put("FOREGROUND_SERVICE", "fore");
        permissionToMessage.put("FOREGROUND_SERVICE_CAMERA", "允许常规应用程序与“相机”类型一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_CAMERA", "camera");
        permissionToMessage.put("FOREGROUND_SERVICE_CONNECTED_DEVICE", "允许常规应用程序与类型“connectedDevice”一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_CONNECTED_DEVICE", "fore");
        permissionToMessage.put("FOREGROUND_SERVICE_DATA_SYNC", "允许常规应用程序与类型“数据同步”一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_DATA_SYNC", "data");
        permissionToMessage.put("FOREGROUND_SERVICE_HEALTH", "允许常规应用程序与类型“运行状况”一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_HEALTH", "fore");
        permissionToMessage.put("FOREGROUND_SERVICE_LOCATION", "允许常规应用程序与类型“位置”一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_LOCATION", "location");
        permissionToMessage.put("FOREGROUND_SERVICE_MEDIA_PLAYBACK", "允许常规应用程序与类型“mediaPlayback”一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_MEDIA_PLAYBACK", "media");
        permissionToMessage.put("FOREGROUND_SERVICE_MEDIA_PROJECTION", "允许常规应用程序与类型“mediaProjection”一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_MEDIA_PROJECTION", "media");
        permissionToMessage.put("FOREGROUND_SERVICE_MICROPHONE", "允许常规应用程序与“麦克风”类型一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_MICROPHONE", "micro");
        permissionToMessage.put("FOREGROUND_SERVICE_PHONE_CALL", "允许常规应用程序与类型“phoneCall”一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_PHONE_CALL", "call");
        permissionToMessage.put("FOREGROUND_SERVICE_REMOTE_MESSAGING", "允许常规应用程序与“远程消息传递”类型一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_REMOTE_MESSAGING", "message");
        permissionToMessage.put("FOREGROUND_SERVICE_SPECIAL_USE", "允许常规应用程序与类型“specialUse”一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_SPECIAL_USE", "fore");
        permissionToMessage.put("FOREGROUND_SERVICE_SYSTEM_EXEMPTED", "允许常规应用程序与类型“系统豁免”一起使用。");
        permissionToProperty.put("FOREGROUND_SERVICE_SYSTEM_EXEMPTED", "fore");
        permissionToMessage.put("GET_ACCOUNTS", "允许访问帐户服务中的帐户列表。");
        permissionToProperty.put("GET_ACCOUNTS", "account");
        permissionToMessage.put("GET_ACCOUNTS_PRIVILEGED", "允许访问帐户服务中的帐户列表。");
        permissionToProperty.put("GET_ACCOUNTS_PRIVILEGED", "account");
        permissionToMessage.put("GET_PACKAGE_SIZE", "允许应用程序找出任何包使用的空间。");
        permissionToProperty.put("GET_PACKAGE_SIZE", "path");
        permissionToMessage.put("GET_TASKS", "暂无。");
        permissionToProperty.put("GET_TASKS", "task");
        permissionToMessage.put("GLOBAL_SEARCH", "此权限可用于内容提供程序，以允许全局搜索系统以访问他们的数据。");
        permissionToProperty.put("GLOBAL_SEARCH", "path");
        permissionToMessage.put("HIDE_OVERLAY_WINDOWS", "允许应用防止在其上绘制非系统覆盖窗口");
        permissionToProperty.put("HIDE_OVERLAY_WINDOWS", "window");
        permissionToMessage.put("HIGH_SAMPLING_RATE_SENSORS", "允许应用访问采样率大于 200 Hz 的传感器数据。");
        permissionToProperty.put("HIGH_SAMPLING_RATE_SENSORS", "sensor");
        permissionToMessage.put("INSTALL_LOCATION_PROVIDER", "允许应用程序将位置提供程序安装到位置管理器中。");
        permissionToProperty.put("INSTALL_LOCATION_PROVIDER", "path");
        permissionToMessage.put("INSTALL_PACKAGES", "允许应用程序安装包。");
        permissionToProperty.put("INSTALL_PACKAGES", "install");
        permissionToMessage.put("INSTALL_SHORTCUT", "允许应用程序在启动器中安装快捷方式。");
        permissionToProperty.put("INSTALL_SHORTCUT", "install");
        permissionToMessage.put("INSTANT_APP_FOREGROUND_SERVICE", "允许免安装应用创建前台服务。");
        permissionToProperty.put("INSTANT_APP_FOREGROUND_SERVICE", "install");
        permissionToMessage.put("INTERACT_ACROSS_PROFILES", "允许在同一配置文件组中的配置文件之间进行交互。");
        permissionToProperty.put("INTERACT_ACROSS_PROFILES", "path");
        permissionToMessage.put("INTERNET", "允许应用程序打开网络套接字。");
        permissionToProperty.put("INTERNET", "net");
        permissionToMessage.put("KILL_BACKGROUND_PROCESSES", "允许应用程序结束后台进程。");
        permissionToProperty.put("KILL_BACKGROUND_PROCESSES", "kill");
        permissionToMessage.put("LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE", "允许应用程序捕获屏幕内容以使用行动。");
        permissionToProperty.put("LAUNCH_CAPTURE_CONTENT_ACTIVITY_FOR_NOTE", "screen");
        permissionToMessage.put("LAUNCH_MULTI_PANE_SETTINGS_DEEP_LINK", "应用程序需要此权限才能在“设置”应用中显示其嵌入的内容。");
        permissionToProperty.put("LAUNCH_MULTI_PANE_SETTINGS_DEEP_LINK", "screen");
        permissionToMessage.put("LOADER_USAGE_STATS", "允许数据加载程序读取包的访问日志。");
        permissionToProperty.put("LOADER_USAGE_STATS", "path");
        permissionToMessage.put("LOCATION_HARDWARE", "允许应用程序使用硬件中的位置功能， 例如地理围栏 API。");
        permissionToProperty.put("LOCATION_HARDWARE", "location");
        permissionToMessage.put("MANAGE_DEVICE_LOCK_STATE", "允许资助的设备自助服务终端应用对设备锁定服务执行操作");
        permissionToProperty.put("MANAGE_DEVICE_LOCK_STATE", "owner");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_ACCESSIBILITY", "允许应用程序管理与辅助功能相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_ACCESSIBILITY", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_ACCOUNT_MANAGEMENT", "允许应用程序设置与帐户管理相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_ACCOUNT_MANAGEMENT", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_ACROSS_USERS", "允许应用程序在当前用户之外设置设备策略 这是在访问用户数据的情况下保护设备所有权所必需的。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_ACROSS_USERS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL", "允许应用程序在当前用户之外设置设备策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_ACROSS_USERS_FULL", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL", "允许应用程序在当前用户之外设置设备策略 这对于保护当前用户中的数据至关重要。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_ACROSS_USERS_SECURITY_CRITICAL", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_AIRPLANE_MODE", "允许应用程序设置与飞行模式相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_AIRPLANE_MODE", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_APPS_CONTROL", "允许应用程序管理有关修改应用程序的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_APPS_CONTROL", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_APP_RESTRICTIONS", "允许应用程序管理应用程序限制。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_APP_RESTRICTIONS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_APP_USER_DATA", "允许应用程序管理与应用程序用户数据相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_APP_USER_DATA", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_AUDIO_OUTPUT", "允许应用程序设置与音频输出相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_AUDIO_OUTPUT", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_AUTOFILL", "允许应用程序设置与自动填充相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_AUTOFILL", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_BACKUP_SERVICE", "允许应用程序管理备份服务策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_BACKUP_SERVICE", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_BLUETOOTH", "允许应用程序设置与蓝牙相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_BLUETOOTH", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_BUGREPORT", "允许应用程序在用户同意的情况下请求错误报告。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_BUGREPORT", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_CALLS", "允许应用程序管理调用策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_CALLS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_CAMERA", "允许应用程序设置与限制用户使用或 启用和禁用相机。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_CAMERA", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_CERTIFICATES", "允许应用程序设置证书相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_CERTIFICATES", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_COMMON_CRITERIA_MODE", "允许应用程序管理与通用条件模式相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_COMMON_CRITERIA_MODE", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_DEBUGGING_FEATURES", "允许应用程序管理调试功能策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_DEBUGGING_FEATURES", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_DEFAULT_SMS", "允许应用程序设置与默认 SMS 应用程序相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_DEFAULT_SMS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_DEVICE_IDENTIFIERS", "允许应用程序管理与设备标识符相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_DEVICE_IDENTIFIERS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_DISPLAY", "允许应用程序设置与显示相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_DISPLAY", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_FACTORY_RESET", "允许应用程序设置与恢复出厂设置相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_FACTORY_RESET", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_FUN", "允许应用程序设置与乐趣相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_FUN", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_INPUT_METHODS", "允许应用程序设置与输入法相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_INPUT_METHODS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_INSTALL_UNKNOWN_SOURCES", "允许应用程序管理从未知源安装策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_INSTALL_UNKNOWN_SOURCES", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_KEEP_UNINSTALLED_PACKAGES", "允许应用程序设置与保留卸载的包相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_KEEP_UNINSTALLED_PACKAGES", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_KEYGUARD", "允许应用程序管理与键盘锁相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_KEYGUARD", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_LOCALE", "允许应用程序设置与区域设置相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_LOCALE", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_LOCATION", "允许应用程序设置与位置相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_LOCATION", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_LOCK", "允许应用程序使用适当的跨用户锁定配置文件或设备 许可。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_LOCK", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_LOCK_CREDENTIALS", "允许应用程序设置与锁定凭据相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_LOCK_CREDENTIALS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_LOCK_TASK", "允许应用程序管理制定任务策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_LOCK_TASK", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_METERED_DATA", "允许应用程序管理与按流量计费的数据相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_METERED_DATA", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_MICROPHONE", "允许应用程序设置与限制用户使用或 启用和禁用麦克风。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_MICROPHONE", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_MOBILE_NETWORK", "允许应用程序设置与移动网络相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_MOBILE_NETWORK", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_MODIFY_USERS", "允许应用程序管理防止用户修改用户的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_MODIFY_USERS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_MTE", "允许应用程序管理与内存标记扩展 （MTE） 相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_MTE", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_NEARBY_COMMUNICATION", "允许应用程序设置与附近通信相关的策略（例如 Beam 和 附近的流媒体）。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_NEARBY_COMMUNICATION", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_NETWORK_LOGGING", "允许应用程序设置与网络日志记录相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_NETWORK_LOGGING", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_ORGANIZATION_IDENTITY", "允许应用程序管理管理组织的标识。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_ORGANIZATION_IDENTITY", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_OVERRIDE_APN", "允许应用程序设置与覆盖 APNs 相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_OVERRIDE_APN", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_PACKAGE_STATE", "允许应用程序设置与隐藏和挂起包相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_PACKAGE_STATE", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_PHYSICAL_MEDIA", "允许应用程序设置与物理媒体相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_PHYSICAL_MEDIA", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_PRINTING", "允许应用程序设置与打印相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_PRINTING", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_PRIVATE_DNS", "允许应用程序设置与私有 DNS 相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_PRIVATE_DNS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_PROFILES", "允许应用程序设置与配置文件相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_PROFILES", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_PROFILE_INTERACTION", "允许应用程序设置与配置文件交互相关的策略（例如，不允许 交叉配置文件复制和粘贴）。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_PROFILE_INTERACTION", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_PROXY", "允许应用程序设置独立于网络的全局 HTTP 代理。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_PROXY", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_QUERY_SYSTEM_UPDATES", "允许应用程序查询系统更新。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_QUERY_SYSTEM_UPDATES", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_RESET_PASSWORD", "允许应用程序强制设置新的设备解锁密码或托管配置文件 对当前用户的挑战。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_RESET_PASSWORD", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_RESTRICT_PRIVATE_DNS", "允许应用程序设置与限制用户配置相关的策略 私有域名系统。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_RESTRICT_PRIVATE_DNS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_RUNTIME_PERMISSIONS", "允许应用程序设置包的运行时权限的授予状态。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_RUNTIME_PERMISSIONS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_RUN_IN_BACKGROUND", "允许应用程序设置与在后台运行的用户相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_RUN_IN_BACKGROUND", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SAFE_BOOT", "允许应用程序管理安全启动策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SAFE_BOOT", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SCREEN_CAPTURE", "允许应用程序设置与屏幕捕获相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SCREEN_CAPTURE", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SCREEN_CONTENT", "允许应用程序设置与屏幕内容使用相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SCREEN_CONTENT", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SECURITY_LOGGING", "允许应用程序设置与安全日志记录相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SECURITY_LOGGING", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SETTINGS", "允许应用程序设置与设置相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SETTINGS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SMS", "允许应用程序设置与短信相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SMS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_STATUS_BAR", "允许应用程序设置与状态栏相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_STATUS_BAR", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SUPPORT_MESSAGE", "允许应用程序设置当用户操作受到 活动策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SUPPORT_MESSAGE", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SUSPEND_PERSONAL_APPS", "允许应用程序设置与挂起个人应用相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SUSPEND_PERSONAL_APPS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SYSTEM_APPS", "允许应用程序管理与系统应用相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SYSTEM_APPS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SYSTEM_DIALOGS", "允许应用程序设置与系统对话框相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SYSTEM_DIALOGS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_SYSTEM_UPDATES", "允许应用程序设置与系统更新相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_SYSTEM_UPDATES", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_TIME", "允许应用程序管理与时间相关的设备策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_TIME", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_USB_DATA_SIGNALLING", "允许应用程序设置与 USB 数据信令相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_USB_DATA_SIGNALLING", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_USB_FILE_TRANSFER", "允许应用程序设备与 USB 文件传输相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_USB_FILE_TRANSFER", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_USERS", "允许应用程序设置与用户相关的策略");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_USERS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_VPN", "允许应用程序设置与 VPN 相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_VPN", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_WALLPAPER", "允许应用程序设置与墙纸相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_WALLPAPER", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_WIFI", "允许应用程序设置与 Wifi 相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_WIFI", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_WINDOWS", "允许应用程序设置与窗口相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_WINDOWS", "policy");
        permissionToMessage.put("MANAGE_DEVICE_POLICY_WIPE_DATA", "允许应用程序管理与擦除数据相关的策略。");
        permissionToProperty.put("MANAGE_DEVICE_POLICY_WIPE_DATA", "policy");
        permissionToMessage.put("MANAGE_DOCUMENTS", "允许应用程序管理对文档的访问，通常作为一部分的文档选取器。");
        permissionToProperty.put("MANAGE_DOCUMENTS", "path");
        permissionToMessage.put("MANAGE_EXTERNAL_STORAGE", "允许应用程序广泛访问作用域存储中的外部存储。");
        permissionToProperty.put("MANAGE_EXTERNAL_STORAGE", "path");
        permissionToMessage.put("MANAGE_MEDIA", "允许应用程序修改和删除此设备或任何连接的媒体文件 无需用户确认的存储设备。");
        permissionToProperty.put("MANAGE_MEDIA", "media");
        permissionToMessage.put("MANAGE_ONGOING_CALLS", "允许查询正在进行的呼叫详细信息和管理正在进行的呼叫");
        permissionToProperty.put("MANAGE_ONGOING_CALLS", "call");
        permissionToMessage.put("MANAGE_OWN_CALLS", "允许调用应用程序通过自我管理的 API 管理自己的调用。ConnectionService");
        permissionToProperty.put("MANAGE_OWN_CALLS", "call");
        permissionToMessage.put("MANAGE_WIFI_INTERFACES", "允许应用程序在 Wi-Fi 接口请求无法时收到通知 在不拆除一个或多个其他接口的情况下感到满意，并提供决策 是批准请求还是拒绝请求。");
        permissionToProperty.put("MANAGE_WIFI_INTERFACES", "wifi");
        permissionToMessage.put("MANAGE_WIFI_NETWORK_SELECTION", "此权限用于允许 OEM 向其受信任的应用授予对 特权 WiFi API，用于提高 WiFi 性能。");
        permissionToProperty.put("MANAGE_WIFI_NETWORK_SELECTION", "wifi");
        permissionToMessage.put("MASTER_CLEAR", "不供第三方应用程序使用。");
        permissionToProperty.put("MASTER_CLEAR", "delete");
        permissionToMessage.put("MEDIA_CONTENT_CONTROL", "允许应用程序知道正在播放的内容并限制其播放。");
        permissionToProperty.put("MEDIA_CONTENT_CONTROL", "media");
        permissionToMessage.put("MODIFY_AUDIO_SETTINGS", "允许应用程序修改全局音频设置。");
        permissionToProperty.put("MODIFY_AUDIO_SETTINGS", "audio");
        permissionToMessage.put("MODIFY_PHONE_STATE", "允许修改电话状态 - 开机、mmi 等。");
        permissionToProperty.put("MODIFY_PHONE_STATE", "call");
        permissionToMessage.put("MOUNT_FORMAT_FILESYSTEMS", "允许格式化可移动存储的文件系统。");
        permissionToProperty.put("MOUNT_FORMAT_FILESYSTEMS", "path");
        permissionToMessage.put("MOUNT_UNMOUNT_FILESYSTEMS", "允许挂载和卸载可移动存储器的文件系统。");
        permissionToProperty.put("MOUNT_UNMOUNT_FILESYSTEMS", "path");
        permissionToMessage.put("NEARBY_WIFI_DEVICES", "需要能够通过 Wi-Fi 播发和连接到附近的设备。");
        permissionToProperty.put("NEARBY_WIFI_DEVICES", "wifi");
        permissionToMessage.put("NFC", "允许应用程序通过 NFC 执行 I/O 操作。");
        permissionToProperty.put("NFC", "nfc");
        permissionToMessage.put("NFC_PREFERRED_PAYMENT_INFO", "允许应用程序接收 NFC 首选支付服务信息。");
        permissionToProperty.put("NFC_PREFERRED_PAYMENT_INFO", "nfc");
        permissionToMessage.put("NFC_TRANSACTION_EVENT", "允许应用程序接收 NFC 事务事件。");
        permissionToProperty.put("NFC_TRANSACTION_EVENT", "nfc");
        permissionToMessage.put("OVERRIDE_WIFI_CONFIG", "允许应用程序修改任何 wifi 配置，即使已创建 通过另一个应用程序。");
        permissionToProperty.put("OVERRIDE_WIFI_CONFIG", "wifi");
        permissionToMessage.put("PACKAGE_USAGE_STATS", "允许应用程序收集组件使用情况 统计学");
        permissionToProperty.put("PACKAGE_USAGE_STATS", "path");
        permissionToMessage.put("PERSISTENT_ACTIVITY", "允许应用程序使其活动持久化。");
        permissionToProperty.put("PERSISTENT_ACTIVITY", "activity");
        permissionToMessage.put("POST_NOTIFICATIONS", "允许应用发布通知");
        permissionToProperty.put("POST_NOTIFICATIONS", "notify");
        permissionToMessage.put("PROCESS_OUTGOING_CALLS", "应用程序应改用广播。");
        permissionToProperty.put("PROCESS_OUTGOING_CALLS", "broad");
        permissionToMessage.put("QUERY_ALL_PACKAGES", "允许查询设备上的任何正常应用，而不考虑清单声明。");
        permissionToProperty.put("QUERY_ALL_PACKAGES", "package");
        permissionToMessage.put("READ_ASSISTANT_APP_SEARCH_DATA", "允许应用程序在 AppSearch 中查询。");
        permissionToProperty.put("READ_ASSISTANT_APP_SEARCH_DATA", "search");
        permissionToMessage.put("READ_BASIC_PHONE_STATE", "允许以非危险权限对电话状态进行只读访问， 包括蜂窝网络类型、软件版本等信息。");
        permissionToProperty.put("READ_BASIC_PHONE_STATE", "call");
        permissionToMessage.put("READ_CALENDAR", "允许应用程序读取用户的日历数据。");
        permissionToProperty.put("READ_CALENDAR", "calendar");
        permissionToMessage.put("READ_CALL_LOG", "允许应用程序读取用户的呼叫日志。");
        permissionToProperty.put("READ_CALL_LOG", "log");
        permissionToMessage.put("READ_CONTACTS", "允许应用程序读取用户的联系人数据。");
        permissionToProperty.put("READ_CONTACTS", "call");
        permissionToMessage.put("READ_EXTERNAL_STORAGE", "允许应用程序从外部存储读取。");
        permissionToProperty.put("READ_EXTERNAL_STORAGE", "path");
        permissionToMessage.put("READ_HOME_APP_SEARCH_DATA", "允许应用程序在 AppSearch 中查询对 家庭角色。");
        permissionToProperty.put("READ_HOME_APP_SEARCH_DATA", "search");
        permissionToMessage.put("READ_INPUT_STATE", "暂无。");
        permissionToProperty.put("READ_INPUT_STATE", "path");
        permissionToMessage.put("READ_LOGS", "允许应用程序读取低级别系统日志文件。");
        permissionToProperty.put("READ_LOGS", "log");
        permissionToMessage.put("READ_MEDIA_AUDIO", "允许应用程序从外部存储读取音频文件。");
        permissionToProperty.put("READ_MEDIA_AUDIO", "audio");
        permissionToMessage.put("READ_MEDIA_IMAGES", "允许应用程序从外部存储读取图像文件。");
        permissionToProperty.put("READ_MEDIA_IMAGES", "image");
        permissionToMessage.put("READ_MEDIA_VIDEO", "允许应用程序从外部存储读取视频文件。");
        permissionToProperty.put("READ_MEDIA_VIDEO", "video");
        permissionToMessage.put("READ_MEDIA_VISUAL_USER_SELECTED", "允许应用程序从用户拥有的外部存储中读取图像或视频文件 通过权限提示照片选择器选择。");
        permissionToProperty.put("READ_MEDIA_VISUAL_USER_SELECTED", "media");
        permissionToMessage.put("READ_NEARBY_STREAMING_POLICY", "允许应用程序读取附近的流式处理策略。");
        permissionToProperty.put("READ_NEARBY_STREAMING_POLICY", "policy");
        permissionToMessage.put("READ_PHONE_NUMBERS", "允许对设备的电话号码进行读取访问。");
        permissionToProperty.put("READ_PHONE_NUMBERS", "number");
        permissionToMessage.put("READ_PHONE_STATE", "允许只读访问电话状态，包括当前蜂窝网络信息， 任何正在进行的呼叫的状态，以及任何呼叫的列表 在设备上注册。");
        permissionToProperty.put("READ_PHONE_STATE", "call");
        permissionToMessage.put("READ_PRECISE_PHONE_STATE", "允许对精确的电话状态进行只读访问。");
        permissionToProperty.put("READ_PRECISE_PHONE_STATE", "call");
        permissionToMessage.put("READ_SMS", "允许应用程序读取短信。");
        permissionToProperty.put("READ_SMS", "sms");
        permissionToMessage.put("READ_SYNC_SETTINGS", "允许应用程序读取同步设置。");
        permissionToProperty.put("READ_SYNC_SETTINGS", "sync");
        permissionToMessage.put("READ_SYNC_STATS", "允许应用程序读取同步统计信息。");
        permissionToProperty.put("READ_SYNC_STATS", "sync");
        permissionToMessage.put("READ_VOICEMAIL", "允许应用程序读取系统中的语音邮件。");
        permissionToProperty.put("READ_VOICEMAIL", "mail");
        permissionToMessage.put("REBOOT", "需要能够重新启动设备。");
        permissionToProperty.put("REBOOT", "boot");
        permissionToMessage.put("RECEIVE_BOOT_COMPLETED", "允许应用程序接收 系统完成引导后广播。");
        permissionToProperty.put("RECEIVE_BOOT_COMPLETED", "boot");
        permissionToMessage.put("RECEIVE_MMS", "允许应用程序监视传入的彩信。");
        permissionToProperty.put("RECEIVE_MMS", "sms");
        permissionToMessage.put("RECEIVE_SMS", "允许应用程序接收 SMS 消息。");
        permissionToProperty.put("RECEIVE_SMS", "sms");
        permissionToMessage.put("RECEIVE_WAP_PUSH", "允许应用程序接收WAP推送消息。");
        permissionToProperty.put("RECEIVE_WAP_PUSH", "wap");
        permissionToMessage.put("RECORD_AUDIO", "允许应用程序录制音频。");
        permissionToProperty.put("RECORD_AUDIO", "audio");
        permissionToMessage.put("REORDER_TASKS", "允许应用程序更改任务的顺序。");
        permissionToProperty.put("REORDER_TASKS", "task");
        permissionToMessage.put("REQUEST_COMPANION_PROFILE_APP_STREAMING", "允许应用程序请求与能够流式传输的虚拟显示器相关联安卓应用。");
        permissionToProperty.put("REQUEST_COMPANION_PROFILE_APP_STREAMING", "compan");
        permissionToMessage.put("REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION", "允许应用程序请求汽车投影。");
        permissionToProperty.put("REQUEST_COMPANION_PROFILE_AUTOMOTIVE_PROJECTION", "compan");
        permissionToMessage.put("REQUEST_COMPANION_PROFILE_COMPUTER", "允许应用程序请求与计算机关联以共享功能和/或其他设备的数据，例如通知、照片和媒体 () 由。");
        permissionToProperty.put("REQUEST_COMPANION_PROFILE_COMPUTER", "compan");
        permissionToMessage.put("REQUEST_COMPANION_PROFILE_GLASSES", "允许应用请求通过“眼镜”与设备关联.");
        permissionToProperty.put("REQUEST_COMPANION_PROFILE_GLASSES", "compan");
        permissionToMessage.put("REQUEST_COMPANION_PROFILE_NEARBY_DEVICE_STREAMING", "允许应用程序请求将内容从 Android 主机流式传输到附近的设备 () 由。");
        permissionToProperty.put("REQUEST_COMPANION_PROFILE_NEARBY_DEVICE_STREAMING", "compan");
        permissionToMessage.put("REQUEST_COMPANION_PROFILE_WATCH", "允许应用程序请求通过“监视”与设备关联.");
        permissionToProperty.put("REQUEST_COMPANION_PROFILE_WATCH", "compan");
        permissionToMessage.put("REQUEST_COMPANION_RUN_IN_BACKGROUND", "允许配套应用在后台运行。");
        permissionToProperty.put("REQUEST_COMPANION_RUN_IN_BACKGROUND", "compan");
        permissionToMessage.put("REQUEST_COMPANION_SELF_MANAGED", "允许应用程序创建“自我管理”关联。");
        permissionToProperty.put("REQUEST_COMPANION_SELF_MANAGED", "compan");
        permissionToMessage.put("REQUEST_COMPANION_START_FOREGROUND_SERVICES_FROM_BACKGROUND", "允许配套应用从后台启动前台服务。");
        permissionToProperty.put("REQUEST_COMPANION_START_FOREGROUND_SERVICES_FROM_BACKGROUND", "compan");
        permissionToMessage.put("REQUEST_COMPANION_USE_DATA_IN_BACKGROUND", "允许配套应用在后台使用数据。");
        permissionToProperty.put("REQUEST_COMPANION_USE_DATA_IN_BACKGROUND", "compan");
        permissionToMessage.put("REQUEST_DELETE_PACKAGES", "允许应用程序请求删除包。");
        permissionToProperty.put("REQUEST_DELETE_PACKAGES", "delete");
        permissionToMessage.put("REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", "应用程序必须持有才能使用的权限。");
        permissionToProperty.put("REQUEST_IGNORE_BATTERY_OPTIMIZATIONS", "device");
        permissionToMessage.put("REQUEST_INSTALL_PACKAGES", "允许应用程序请求安装包。");
        permissionToProperty.put("REQUEST_INSTALL_PACKAGES", "install");
        permissionToMessage.put("REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE", "允许应用程序订阅有关状态更改的通知其关联的配套设备。");
        permissionToProperty.put("REQUEST_OBSERVE_COMPANION_DEVICE_PRESENCE", "compan");
        permissionToMessage.put("REQUEST_PASSWORD_COMPLEXITY", "允许应用程序请求屏幕锁定复杂性，并提示用户更新屏幕锁定到一定复杂程度。");
        permissionToProperty.put("REQUEST_PASSWORD_COMPLEXITY", "pwd");
        permissionToMessage.put("RESTART_PACKAGES", "暂无。");
        permissionToProperty.put("RESTART_PACKAGES", "path");
        permissionToMessage.put("RUN_USER_INITIATED_JOBS", "允许应用程序使用用户启动的作业 API。");
        permissionToProperty.put("RUN_USER_INITIATED_JOBS", "user");
        permissionToMessage.put("SCHEDULE_EXACT_ALARM", "允许应用程序使用精确的警报 API。");
        permissionToProperty.put("SCHEDULE_EXACT_ALARM", "alarm");
        permissionToMessage.put("SEND_RESPOND_VIA_MESSAGE", "允许应用程序（电话）向其他应用程序发送请求在传入呼叫期间处理通过消息响应操作。");
        permissionToProperty.put("SEND_RESPOND_VIA_MESSAGE", "message");
        permissionToMessage.put("SEND_SMS", "允许应用程序发送 SMS 消息。");
        permissionToProperty.put("SEND_SMS", "sms");
        permissionToMessage.put("SET_ALARM", "允许应用程序广播意图以用户设置警报。");
        permissionToProperty.put("SET_ALARM", "alarm");
        permissionToMessage.put("SET_ALWAYS_FINISH", "允许应用程序控制活动是否立即进行，放在后台完成。");
        permissionToProperty.put("SET_ALWAYS_FINISH", "fore");
        permissionToMessage.put("SET_ANIMATION_SCALE", "修改全局动画比例因子。");
        permissionToProperty.put("SET_ANIMATION_SCALE", "anima");
        permissionToMessage.put("SET_DEBUG_APP", "配置应用程序以进行调试。");
        permissionToProperty.put("SET_DEBUG_APP", "debug");
        permissionToMessage.put("SET_PREFERRED_APPLICATIONS", "暂无。");
        permissionToProperty.put("SET_PREFERRED_APPLICATIONS", "owner");
        permissionToMessage.put("SET_PROCESS_LIMIT", "允许应用程序设置最大数量（不需要） 可以运行的应用程序进程。");
        permissionToProperty.put("SET_PROCESS_LIMIT", "limit");
        permissionToMessage.put("SET_TIME", "允许应用程序直接设置系统时间。");
        permissionToProperty.put("SET_TIME", "time");
        permissionToMessage.put("SET_TIME_ZONE", "允许应用程序直接设置系统时区。");
        permissionToProperty.put("SET_TIME_ZONE", "time");
        permissionToMessage.put("SET_WALLPAPER", "允许应用程序设置墙纸。");
        permissionToProperty.put("SET_WALLPAPER", "wall");
        permissionToMessage.put("SET_WALLPAPER_HINTS", "允许应用程序设置墙纸提示。");
        permissionToProperty.put("SET_WALLPAPER_HINTS", "wall");
        permissionToMessage.put("SIGNAL_PERSISTENT_PROCESSES", "允许应用程序请求将信号发送到所有持久进程。");
        permissionToProperty.put("SIGNAL_PERSISTENT_PROCESSES", "message");
        permissionToMessage.put("SMS_FINANCIAL_TRANSACTIONS", "暂无。");
        permissionToProperty.put("SMS_FINANCIAL_TRANSACTIONS", "sms");
        permissionToMessage.put("START_FOREGROUND_SERVICES_FROM_BACKGROUND", "允许应用程序随时从后台启动前台服务。");
        permissionToProperty.put("START_FOREGROUND_SERVICES_FROM_BACKGROUND", "fore");
        permissionToMessage.put("START_VIEW_APP_FEATURES", "允许持有者使用应用程序功能列表启动屏幕。");
        permissionToProperty.put("START_VIEW_APP_FEATURES", "screen");
        permissionToMessage.put("START_VIEW_PERMISSION_USAGE", "允许持有者启动应用程序的权限使用屏幕。");
        permissionToProperty.put("START_VIEW_PERMISSION_USAGE", "screen");
        permissionToMessage.put("STATUS_BAR", "允许应用程序打开、关闭或禁用状态栏 及其图标。");
        permissionToProperty.put("STATUS_BAR", "bar");
        permissionToMessage.put("SUBSCRIBE_TO_KEYGUARD_LOCKED_STATE", "允许应用程序订阅键盘锁锁定（即显示）状态。");
        permissionToProperty.put("SUBSCRIBE_TO_KEYGUARD_LOCKED_STATE", "key");
        permissionToMessage.put("SYSTEM_ALERT_WINDOW", "允许应用使用类型 创建窗口 ， 显示在所有其他应用程序的顶部。");
        permissionToProperty.put("SYSTEM_ALERT_WINDOW", "window");
        permissionToMessage.put("TRANSMIT_IR", "允许使用设备的红外发射器（如果可用）。");
        permissionToProperty.put("TRANSMIT_IR", "ir");
        permissionToMessage.put("TURN_SCREEN_ON", "允许应用程序打开屏幕。");
        permissionToProperty.put("TURN_SCREEN_ON", "screen");
        permissionToMessage.put("UNINSTALL_SHORTCUT", "请勿在应用中使用此权限。");
        permissionToProperty.put("UNINSTALL_SHORTCUT", "install");
        permissionToMessage.put("UPDATE_DEVICE_STATS", "允许应用程序更新设备统计信息。");
        permissionToProperty.put("UPDATE_DEVICE_STATS", "device");
        permissionToMessage.put("UPDATE_PACKAGES_WITHOUT_USER_ACTION", "允许应用程序通过指示应用更新不需要用户操作。");
        permissionToProperty.put("UPDATE_PACKAGES_WITHOUT_USER_ACTION", "update");
        permissionToMessage.put("USE_BIOMETRIC", "允许应用使用设备支持的生物识别模式。");
        permissionToProperty.put("USE_BIOMETRIC", "biom");
        permissionToMessage.put("USE_EXACT_ALARM", "允许应用使用精确的警报，就像使用一样，但无需请求此警报 来自用户的权限。");
        permissionToProperty.put("USE_EXACT_ALARM", "alarm");
        permissionToMessage.put("USE_FINGERPRINT", "暂无。");
        permissionToProperty.put("USE_FINGERPRINT", "biom");
        permissionToMessage.put("USE_FULL_SCREEN_INTENT", "对于要使用的定位应用是必需的。");
        permissionToProperty.put("USE_FULL_SCREEN_INTENT", "screen");
        permissionToMessage.put("USE_ICC_AUTH_WITH_DEVICE_IDENTIFIER", "允许读取设备标识符并使用基于 ICC 的身份验证，如 EAP-AKA。");
        permissionToProperty.put("USE_ICC_AUTH_WITH_DEVICE_IDENTIFIER", "device");
        permissionToMessage.put("USE_SIP", "允许应用程序使用 SIP 服务。");
        permissionToProperty.put("USE_SIP", "sip");
        permissionToMessage.put("UWB_RANGING", "需要能够扩展到使用超宽带的设备。");
        permissionToProperty.put("UWB_RANGING", "net");
        permissionToMessage.put("VIBRATE", "允许访问振动器。");
        permissionToProperty.put("VIBRATE", "vibrate");
        permissionToMessage.put("WAKE_LOCK", "允许使用电源管理器唤醒锁来防止处理器进入睡眠或屏幕 从调暗。");
        permissionToProperty.put("WAKE_LOCK", "screen");
        permissionToMessage.put("WRITE_APN_SETTINGS", "允许应用程序写入 apn 设置并读取敏感字段 现有的 APN 设置，如用户名、密码。");
        permissionToProperty.put("WRITE_APN_SETTINGS", "apn");
        permissionToMessage.put("WRITE_CALENDAR", "允许应用程序写入用户的日历数据。");
        permissionToProperty.put("WRITE_CALENDAR", "calendar");
        permissionToMessage.put("WRITE_CALL_LOG", "允许应用程序写入（但不读取）用户的 通话记录数据。");
        permissionToProperty.put("WRITE_CALL_LOG", "log");
        permissionToMessage.put("WRITE_CONTACTS", "允许应用程序写入用户的联系人数。");
        permissionToProperty.put("WRITE_CONTACTS", "call");
        permissionToMessage.put("WRITE_EXTERNAL_STORAGE", "允许应用程序写入外部存储。");
        permissionToProperty.put("WRITE_EXTERNAL_STORAGE", "path");
        permissionToMessage.put("WRITE_GSERVICES", "允许应用程序修改谷歌服务映射。");
        permissionToProperty.put("WRITE_GSERVICES", "google");
        permissionToMessage.put("WRITE_SECURE_SETTINGS", "允许应用程序读取或写入安全系统设置。");
        permissionToProperty.put("WRITE_SECURE_SETTINGS", "secur");
        permissionToMessage.put("WRITE_SETTINGS", "允许应用程序读取或写入系统设置。");
        permissionToProperty.put("WRITE_SETTINGS", "user");
        permissionToMessage.put("WRITE_SYNC_SETTINGS", "允许应用程序写入同步设置。");
        permissionToProperty.put("WRITE_SYNC_SETTINGS", "sync");
        permissionToMessage.put("WRITE_VOICEMAIL", "允许应用程序修改和删除系统中的现有语音邮件。");
        permissionToProperty.put("WRITE_VOICEMAIL", "mail");
    }
}
